---
- name: Configure Apache virtual host
  hosts: web
  become: true

  vars:
    virtual_host_name: example.com
    virtual_host_port: 8080
    virtual_host_directory: /var/web
    virtual_host_log_directory: /var/log/httpd

  tasks:
    - name: Install Apache web server
      ansible.builtin.dnf:
        name: httpd
        state: present

    - name: Create virtual host directory
      file:
        path: "{{ virtual_host_directory }}"
        state: directory
        owner: apache
        group: apache
        mode: '0755'
    
    - name: Correct index.html is present
      ansible.builtin.copy:
        src: files/index.html
        dest: /var/www/html/index.html
    
    - name: Enable virtual host logging
      file:
        path: "{{ virtual_host_log_directory }}/{{ virtual_host_name }}.log"
        state: touch
        owner: apache
        group: apache
        mode: '0644'

    - name: Restart Apache service
      service:
        name: httpd
        state: restarted
