---
- name: Configure SSH port
  hosts: web
  become: true

  vars:
    ssh_port: 28222
 
  tasks:
    - name: Change SSH port in sshd_config
      become: true
      replace:
        path: /etc/ssh/sshd_config
        regexp: '^\s*#?\s*Port\s+\d+'
        replace: 'Port {{ ssh_port }}'
    
    - name: Apply SELinux context to new SSH port
      become: true  
      community.general.seport:
        ports: '{{ ssh_port }}'
        proto: tcp
        setype: ssh_port_t
        state: present
      notify: Restart SSH

  handlers:
    - name: Restart SSH
      become: true
      service:  
        name: sshd
        state: restarted
