---
- name: Use myvhost role playbook
  hosts: web
  pre_tasks:
    - name: pre_tasks message
      ansible.builtin.debug:
        msg: 'Ensure web server configuration.'
      
  roles:  
    - apache

  post_tasks:
    - name: HTML content is installed
      ansible.builtin.copy:
        src: roles/apache/files/html/
        dest: "/var/www/vhosts/{{ ansible_hostname }}"

    - name: post_tasks message
      ansible.builtin.debug:
        msg: 'Web server is configured.'
