---
- name: Configure SSH port
  hosts: web

  pre_tasks:
    - name: pre_tasks message
      ansible.builtin.debug:
        msg: 'Ensure SSH configuration.'
      
  roles:  
    - ssh

  post_tasks:
    - name: post_tasks message
      ansible.builtin.debug:
        msg: 'SSH is configured.'
