---
- name: Change hostname to web.example.org
  hosts: web

  pre_tasks:
    - name: pre_tasks message
      ansible.builtin.debug:
        msg: 'Ensure hostname configuration.'
      
  roles:  
    - hostname

  post_tasks:
    - name: post_tasks message
      ansible.builtin.debug:
        msg: 'Hostname is configured.'
